language: rust
rust: nightly
sudo: false

before_script:
  - cargo install clippy || true
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo test --all --all-features
  - |
    if command -v cargo-clippy > /dev/null; then
      CLIPPY_STATUS=0
      for package in maud_htmlescape maud_macros maud maud_extras; do
        cargo clippy --manifest-path $package/Cargo.toml -- -D warnings || CLIPPY_STATUS=$?
      done
      (exit $CLIPPY_STATUS)
    fi
