language: rust
rust: nightly
sudo: false

before_script:
  - |
    RUN_CLIPPY=true
    rustup component add clippy --toolchain=nightly || RUN_CLIPPY=false

script:
  - cargo test --all --all-features
  - (cd benchmarks && cargo bench --no-run)
  - |
    if $RUN_CLIPPY; then
      CLIPPY_STATUS=0
      for package in maud_htmlescape maud_macros maud; do
        (cd $package && cargo clippy -- -D warnings) || CLIPPY_STATUS=$?
      done
      (exit $CLIPPY_STATUS)
    fi
