env:
  global:
    - secure: aXA1rURuwGHa+JpCv3bkff8glnWI77bAPYJ4T06Fyst9r9PooA0TvPKFl2UK2hkVoZmqm9sF/mxBnQJ/hh4vfDHDGSmgLZCRFa9hHtRRQyXPmDCfbWXdw6rhT9EH4QWxDeFcxHSeVLquenOCXDxLG/pmMXLqbYy7iA57WmiNcUo=
language: rust
script:
  - ( cd maud_macros && cargo build --verbose && cargo test --verbose && cargo doc --verbose )
after_script:
  - mv maud_macros/target/doc doc && curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
