[package]

name = "maud"
version = "0.10.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://lambda.xyz/maud/maud/"
homepage = "http://lfairy.gitbooks.io/maud/content/"
repository = "https://github.com/lfairy/maud"
description = """
Compile-time HTML templates.
"""

[dependencies]
iron = { version = "0.4.0", optional = true }
