[package]

name = "maud_macros"
version = "0.8.1"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://lambda.xyz/maud/maud/"
homepage = "http://lfairy.gitbooks.io/maud/content/"
repository = "https://github.com/lfairy/maud"
description = """
Compile-time HTML templates.
"""

[dependencies.maud]
path = "../maud"
version = "=0.8.1"

[lib]
name = "maud_macros"
plugin = true
