[package]

name = "maud_macros"
version = "0.16.3"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://lambda.xyz/maud/maud/"
homepage = "https://maud.lambda.xyz/"
repository = "https://github.com/lfairy/maud"
description = "Compile-time HTML templates."

[dependencies]
if_chain = "0.1"
maud = { path = "../maud", version = "0.16.0" }

[lib]
name = "maud_macros"
plugin = true

[badges]
travis-ci = { repository = "lfairy/maud" }
