[package]

name = "maud_macros"
version = "0.1.2"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://lambda.xyz/maud/doc/maud/"
repository = "https://github.com/lfairy/maud"
description = """
Compile-time HTML templates.
"""

[dependencies.maud]
path = "../maud"
version = "=0.1.2"

[lib]
name = "maud_macros"
plugin = true
