[package]

name = "htmlthing"
version = "0.0.1"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
repository = "https://github.com/lfairy/htmlthing"
description = """
Compile-time HTML templates.
"""
